### ISSUE TITLE
Flutter material introduced a `Badge` widget as well

### ISSUE THREAD

**Issue by robiness** [yako-dev/flutter_badges#96]
Flutter material [introduced a Badge widget on its own ](https://github.com/flutter/flutter/pull/114560)
So when using this package in the current master as mentioned in #78 we get a [ambiguous_import](ambiguous_import).

As an easy fix i did `import 'package:badges/badges.dart' as badges`. 
But this package may wants to tackle this in another way.

To test just use this with the current master.

**Comment by yadaniyil** [comment]
Thanks for letting me know, @robiness. That's interesting how our package should be changed due to the new Material widget. 
It's either `import 'package:badges/badges.dart' as badges` or change the package to the 
`import 'package:flutter_badges/flutter_badges.dart`. Don't know the most correct way yet.
